### ISSUE TITLE
Missing direct message form on the bottom of 'Become a Corporate Sponsor' page

### ISSUE THREAD

**Issue by nico-primak** [PeaceGeeksSociety/PeaceGeeks-Website#104] opened 2015-09-22 23:40 UTC
Please refer to the designs and annotations for the Take Action section. Annotation numbers are 18 and 19.

**Comment by reallyordinary** [comment] 2015-09-23 06:29
This is a duplicate of this - https://github.com/PeaceGeeksSociety/PeaceGeeks-Website/issues/96

**Closed** 2015-09-24 06:10 UTC
Labels: Theming, Urgent
